spring:
  application:
    name: Backend
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/greenplore}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:anilsa3omsa}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
  devtools:
    restart:
      enabled: false
logging:
  level:
    root: info

rzp:
  key-id: ${RZP_KEY_ID:rzp_live_RCemjVt0zfY8v2}           # Use environment variable
  key-secret: ${RZP_KEY_SECRET:Os5ZmY05N1NT3Ck3YQ7uZnDZ}   # Use environment variable
  currency: INR
  company-name: MyCompany

nimbus:
  token: ${NIMBUS_TOKEN:Os5ZmY05N1NT3Ck3YQ7uZnDZ}

frontend-url: ${FRONTEND_URL:http://localhost:5173}