spring:
  application:
    name: Backend
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/greenplore}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:anilsa3omsa}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
  devtools:
    restart:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: infogreenplore@gmail.com
    password: xcvcnwrblfmqgsak
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
logging:
  level:
    root: info

rzp:
  key-id: ${RZP_KEY_ID:rzp_live_RCemjVt0zfY8v2}           # Use environment variable
  key-secret: ${RZP_KEY_SECRET:Os5ZmY05N1NT3Ck3YQ7uZnDZ}   # Use environment variable
  currency: INR
  company-name: MyCompany

nimbus:
  token: ${NIMBUS_TOKEN:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NTg5NjY0ODgsImp0aSI6IlVuVkU3TUhTYktBWk84XC8zRzF4bFJUaldsTTRKdHcwUU5mZmFyQndoVG5jPSIsIm5iZiI6MTc1ODk2NjQ4OCwiZXhwIjoxNzU4OTc3Mjg4LCJkYXRhIjp7InVzZXJfaWQiOiIyMTY5MTIiLCJwYXJlbnRfaWQiOiIwIn19.JIe7kYFtwnNJDWmlXaRQqXdNZHJ4B7UBPvCbg0lyZToxWef8bH1idUssPIpnJSBQez-sWwhzmJeEF9rSXEiQsw}

frontend-url: ${FRONTEND_URL:http://localhost:5173}