spring:
  application:
    name: Backend
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/greenplore}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:anilsa3omsa}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
  devtools:
    restart:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: infogreenplore@gmail.com
    password: xcvcnwrblfmqgsak
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
logging:
  level:
    root: info

rzp:
  key-id: ${RZP_KEY_ID:demo}           # Use environment variable
  key-secret: ${RZP_KEY_SECRET:demo}   # Use environment variable
  currency: INR
  company-name: MyCompany

nimbus:
  username: ${NIMBUS_USERNAME:infogreenplore@gmail.com}
  password: ${NIMBUS_PASSWORD:Delhi@gp_12}

frontend-url: ${FRONTEND_URL:http://localhost:5173}