spring:
  application:
    name: Backend
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/greenplore
    username: root
    password: anilsa3omsa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

